version: "3.8"

services:
  sonarqube:
    image: sonarqube:25.4.0.105899-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - sonarqube_network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Dnode.store.allow_mmap=false
      - SONAR_WEB_JAVAADDITIONALOPTS=-Dnode.store.allow_mmap=false

  db:
    image: postgres
    container_name: sonarqube_db
    networks:
      - sonarqube_network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  sonarqube_network:

volumes:
  sonarqube_data:
  postgres_data:

